package com.agenthub.runtime.mock;

import com.agenthub.domain.agent.model.AgentExecutionRequest;
import com.agenthub.execution.domain.model.CancelToken;
import com.agenthub.runtime.port.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

import java.io.File;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.List;
import java.util.UUID;
import java.util.concurrent.CompletableFuture;

/**
 * Mock Agent Runtime for deterministic testing and offline simulation.
 * Clearly flags simulated=true and respects CancelToken.
 */
@Component("mockAgentRuntime")
public class MockAgentRuntime implements AgentRuntime {

    private static final Logger log = LoggerFactory.getLogger(MockAgentRuntime.class);

    @Override
    public RuntimeDescriptor describe() {
        return new RuntimeDescriptor(
                "MOCK",
                "AgentHub Simulated Offline Engine",
                "1.0.0-mock",
                "AgentHub-Simulator",
                List.of("CODE_GENERATION", "MOCK_TOOLS", "STREAMING"),
                true
        );
    }

    @Override
    public RuntimeHealth checkHealth() {
        return RuntimeHealth.ok("Mock runtime ready and operational", 1);
    }

    @Override
    public ExecutionHandle start(AgentExecutionRequest request, RuntimeEventSink sink, CancelToken cancelToken) {
        String handleId = "handle-mock-" + UUID.randomUUID().toString().substring(0, 8);
        String runId = request.getAgentName() != null ? request.getAgentName() : "run-default";
        String stepRunId = "step-mock-" + UUID.randomUUID().toString().substring(0, 8);
        ExecutionHandle handle = new ExecutionHandle(handleId, runId, stepRunId, "MOCK");

        CompletableFuture.runAsync(() -> {
            try {
                if (cancelToken != null && cancelToken.isCancelled()) {
                    sink.onStepFailed(runId, stepRunId, "Execution cancelled before start: " + cancelToken.getReason(), null);
                    return;
                }

                sink.onLog(runId, stepRunId, "INFO", "Initializing mock agent execution for task: " + request.getPrompt());

                // Simulated slow delay if task requested slow processing
                if (request.getPrompt() != null && (request.getPrompt().toLowerCase().contains("slow") || request.getPrompt().contains("超长等待"))) {
                    for (int i = 0; i < 40; i++) {
                        if (cancelToken != null && cancelToken.isCancelled()) {
                            sink.onStepFailed(runId, stepRunId, "Execution cancelled during slow step: " + cancelToken.getReason(), null);
                            return;
                        }
                        Thread.sleep(100);
                    }
                }

                // Simulated tokens
                String[] tokens = {"Analyzing", " task", " requirements...", " Generating", " solution", " code."};
                for (String t : tokens) {
                    if (cancelToken != null && cancelToken.isCancelled()) {
                        sink.onStepFailed(runId, stepRunId, "Cancelled during streaming", null);
                        return;
                    }
                    sink.onToken(runId, stepRunId, t);
                    try {
                        Thread.sleep(10);
                    } catch (InterruptedException e) {
                        Thread.currentThread().interrupt();
                        sink.onStepFailed(runId, stepRunId, "Interrupted during mock stream", e);
                        return;
                    }
                }

                // Simulated Tool Call
                sink.onToolCall(runId, stepRunId, "workspace_file_writer", "{\"file\":\"MockService.java\"}");

                // Workspace File Generation if path provided
                if (request.getWorkspacePath() != null) {
                    File dir = new File(request.getWorkspacePath());
                    if (!dir.exists()) dir.mkdirs();
                    File mockFile = new File(dir, "MockService.java");
                    Files.writeString(mockFile.toPath(),
                            "package com.agenthub.generated;\n\npublic class MockService {\n    // Generated by MockAgentRuntime\n}\n",
                            StandardCharsets.UTF_8);
                    sink.onFileChange(runId, stepRunId, "MockService.java", "CREATED");
                }

                sink.onUsage(runId, stepRunId, 120, 250, 0.0004);

                String finalOutput = "// Generated by MockAgentRuntime\npublic class MockService {\n    public String hello() {\n        return \"ok\";\n    }\n}";
                sink.onStepCompleted(runId, stepRunId, finalOutput);
            } catch (Exception e) {
                log.error("Mock runtime execution failed: {}", e.getMessage(), e);
                sink.onStepFailed(runId, stepRunId, e.getMessage(), e);
            }
        });

        return handle;
    }

    @Override
    public void cancel(ExecutionHandle handle) {
        if (handle != null) {
            handle.markCancelled();
        }
    }
}
