package com.agenthub;

import com.agenthub.execution.application.ExecutionApplication;
import com.agenthub.execution.domain.model.CancelTokenRegistry;
import com.agenthub.execution.domain.model.WorkflowRunStatus;
import com.agenthub.execution.dto.RunEventView;
import com.agenthub.execution.dto.StartRunCommand;
import com.agenthub.execution.dto.WorkflowRunView;
import com.agenthub.execution.scheduler.ExecutionScheduler;
import com.agenthub.execution.scheduler.ExecutionScheduler.ScheduledTaskNode;
import com.agenthub.shared.context.RequestContext;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

import java.io.File;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.TimeUnit;

import static org.assertj.core.api.Assertions.assertThat;

@SpringBootTest
@ActiveProfiles("test")
class ExecutionSchedulerAndRuntimeIntegrationTest {

    @Autowired
    private ExecutionApplication executionApplication;

    @Autowired
    private ExecutionScheduler executionScheduler;

    @Autowired
    private CancelTokenRegistry cancelTokenRegistry;

    @BeforeEach
    void setUp() {
        RequestContext.get().setUserId("user-1");
    }

    @AfterEach
    void tearDown() {
        RequestContext.clear();
    }

    @Test
    @DisplayName("测试调度器驱动真实执行解耦：调度器只负责状态机编排与事件发布，执行细节委派给 MockAgentRuntime")
    void shouldExecuteDecoupledScheduledRunSuccessfully(@TempDir File workspaceDir) throws Exception {
        WorkflowRunView run = executionApplication.startRun(new StartRunCommand("proj-default", "def-default", null));
        String runId = run.getId();

        List<ScheduledTaskNode> nodes = List.of(
                new ScheduledTaskNode("backend-task", "后端架构设计", "MOCK", "设计核心服务接口"),
                new ScheduledTaskNode("qa-task", "QA 质量审计", "MOCK", "审计测试覆盖率与边界防御")
        );

        CompletableFuture<WorkflowRunStatus> future = executionScheduler.scheduleRun(
                runId,
                nodes,
                workspaceDir.getAbsolutePath(),
                30
        );

        WorkflowRunStatus finalStatus = future.get(10, TimeUnit.SECONDS);
        assertThat(finalStatus).isEqualTo(WorkflowRunStatus.SUCCEEDED);

        WorkflowRunView finishedRun = executionApplication.getRunById(runId);
        assertThat(finishedRun.getStatus()).isEqualTo("SUCCEEDED");
        assertThat(finishedRun.getFinishedAt()).isNotNull();

        // Workspace file must have been generated by MockAgentRuntime
        File generatedFile = new File(workspaceDir, "MockService.java");
        assertThat(generatedFile).exists();

        // Events must contain tokens, tool calls, and completion
        List<RunEventView> events = executionApplication.listEvents(runId, null);
        assertThat(events.stream().anyMatch(e -> "TOKEN".equals(e.getEventType()))).isTrue();
        assertThat(events.stream().anyMatch(e -> "TOOL_CALL".equals(e.getEventType()))).isTrue();
        assertThat(events.stream().anyMatch(e -> "STEP_COMPLETED".equals(e.getEventType()))).isTrue();
        assertThat(events.stream().anyMatch(e -> "RUN_COMPLETED".equals(e.getEventType()))).isTrue();
    }

    @Test
    @DisplayName("测试调度器在运行期间响应协作取消：立即中断剩余 Step，状态机收敛为 CANCELLED")
    void shouldCancelScheduledRunWithinScheduler() throws Exception {
        WorkflowRunView run = executionApplication.startRun(new StartRunCommand("proj-default", "def-default", null));
        String runId = run.getId();

        List<ScheduledTaskNode> nodes = List.of(
                new ScheduledTaskNode("step-long-1", "长周期计算任务 1", "MOCK", "执行长耗时推理"),
                new ScheduledTaskNode("step-long-2", "长周期计算任务 2", "MOCK", "第二阶段任务")
        );

        CompletableFuture<WorkflowRunStatus> future = executionScheduler.scheduleRun(
                runId,
                nodes,
                null,
                30
        );

        // Cancel while running
        Thread.sleep(15);
        cancelTokenRegistry.cancel(runId, "Aborted by test trigger");

        WorkflowRunStatus finalStatus = future.get(5, TimeUnit.SECONDS);
        assertThat(finalStatus).isEqualTo(WorkflowRunStatus.CANCELLED);

        WorkflowRunView cancelledRun = executionApplication.getRunById(runId);
        assertThat(cancelledRun.getStatus()).isEqualTo("CANCELLED");
    }

    @Test
    @DisplayName("测试调度器超时强平看门狗：执行超过限定时限自动触发强平，收敛为 TIMED_OUT")
    void shouldEnforceWatchdogTimeoutInScheduler() throws Exception {
        WorkflowRunView run = executionApplication.startRun(new StartRunCommand("proj-default", "def-default", null));
        String runId = run.getId();

        List<ScheduledTaskNode> nodes = List.of(
                new ScheduledTaskNode("task-slow", "慢速任务", "MOCK", "执行超长等待")
        );

        // Set effective timeout of 1 second
        CompletableFuture<WorkflowRunStatus> future = executionScheduler.scheduleRun(
                runId,
                nodes,
                null,
                1
        );

        // Wait for watchdog to trigger
        Thread.sleep(1200);

        WorkflowRunStatus status = future.get(5, TimeUnit.SECONDS);
        assertThat(status).isEqualTo(WorkflowRunStatus.TIMED_OUT);

        WorkflowRunView timedOutRun = executionApplication.getRunById(runId);
        assertThat(timedOutRun.getStatus()).isEqualTo("TIMED_OUT");
        assertThat(timedOutRun.getCancelReason()).containsIgnoringCase("timeout");
    }
}
