package com.agenthub;

import com.agenthub.domain.agent.model.AgentPlatformType;
import com.agenthub.domain.workflow.model.WorkflowModels.*;
import com.agenthub.domain.workflow.service.WorkflowEngineService;
import com.agenthub.domain.workspace.model.FileDiffEntry;
import com.agenthub.domain.workspace.service.JGitWorkspaceManager;
import com.agenthub.infrastructure.concurrency.WorkspaceLockManager;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

import java.io.File;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.List;

import org.springframework.test.context.ActiveProfiles;

import static org.assertj.core.api.Assertions.assertThat;

@SpringBootTest
@ActiveProfiles("test")
class WorkflowAndJGitTest {

    @Autowired
    private JGitWorkspaceManager gitManager;

    @Autowired
    private WorkspaceLockManager lockManager;

    @Autowired
    private WorkflowEngineService workflowEngineService;

    @Test
    @DisplayName("测试 JGit 工作区初始化及生成代码修改的行级准确 Diff")
    void shouldInitializeWorkspaceAndGenerateAccurateDiff(@TempDir File tempDir) throws Exception {
        // 1. Initialize Baseline
        gitManager.initWorkspace(tempDir);
        assertThat(new File(tempDir, ".git")).exists();

        // 2. Add a new file generated by an Agent
        File newCodeFile = new File(tempDir, "UserController.java");
        Files.writeString(newCodeFile.toPath(), "public class UserController {\n    // Agent Generated\n}\n", StandardCharsets.UTF_8);

        // 3. Compute Diff
        List<FileDiffEntry> diffs = gitManager.computeWorkspaceDiff(tempDir);
        assertThat(diffs).isNotEmpty();
        FileDiffEntry entry = diffs.get(0);
        assertThat(entry.getNewPath()).contains("UserController.java");
        assertThat(entry.getLinesAdded()).isGreaterThan(0);
        assertThat(entry.getDiffContent()).contains("UserController");
    }

    @Test
    @DisplayName("测试 WorkspaceLockManager 防并发锁机制")
    void shouldPreventConcurrentLocking() {
        String path = "./target/test-workspaces/lock-1";
        boolean firstLock = lockManager.tryLock(path, 100);
        assertThat(firstLock).isTrue();

        // Another thread trying to acquire lock should fail immediately or timeout
        boolean[] secondLock = new boolean[1];
        Thread t = new Thread(() -> {
            secondLock[0] = lockManager.tryLock(path, 50);
        });
        t.start();
        try {
            t.join();
        } catch (InterruptedException ignored) {}

        assertThat(secondLock[0]).isFalse();
        lockManager.unlock(path);
    }

    @Test
    @DisplayName("测试 DAG 工作流多节点拓扑编排与上下文传递")
    void shouldExecuteDagWorkflowSuccessfully(@TempDir File tempDir) {
        WorkflowDefinition workflow = new WorkflowDefinition();
        workflow.setId("wf-test-dag");
        workflow.setName("前后端协同工作流");

        NodeDefinition startNode = new NodeDefinition("start", "开始节点", NodeType.START, null, null);
        startNode.getNextNodeIds().add("backend-node");

        NodeDefinition backendNode = new NodeDefinition(
                "backend-node",
                "后端API设计",
                NodeType.AGENT,
                AgentPlatformType.SPRING_AI_API,
                "设计用户注册登录API"
        );
        backendNode.getNextNodeIds().add("frontend-node");

        NodeDefinition frontendNode = new NodeDefinition(
                "frontend-node",
                "前端组件构建",
                NodeType.AGENT,
                AgentPlatformType.SPRING_AI_API,
                "基于上述API构建登录表单"
        );
        frontendNode.getNextNodeIds().add("end-node");

        NodeDefinition endNode = new NodeDefinition("end-node", "结束节点", NodeType.END, null, null);

        workflow.getNodes().addAll(List.of(startNode, backendNode, frontendNode, endNode));

        WorkflowExecutionResult result = workflowEngineService.executeWorkflow(
                workflow,
                tempDir.getAbsolutePath(),
                "构建系统认证模块"
        );

        assertThat(result).isNotNull();
        assertThat(result.getStatus()).isEqualTo(ExecutionStatus.SUCCEEDED);
        assertThat(result.getNodeStates().get("backend-node").getStatus()).isEqualTo(ExecutionStatus.SUCCEEDED);
        assertThat(result.getNodeStates().get("frontend-node").getStatus()).isEqualTo(ExecutionStatus.SUCCEEDED);
        assertThat(result.getFinalOutput()).isNotEmpty();
    }
}
